### ISSUE TITLE
Concurrency issues using SQLite in development

### ISSUE THREAD

**Issue by andrewhavens** [mperham/sidekiq#1487]
My app has some fast running jobs which make multiple checks/updates in the database. The error that is occasionally being raised is:

```
SQLite3::BusyException: database is locked
```

At first I thought this was a connection pooling issue, so I increased the default pool limit to match the Sidekiq concurrency setting:

``` yml
# database.yml
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 25
  timeout: 10000

# sidekiq.yml

---
:concurrency: 25 # default is 25
```

I restarted sidekiq, but that did not fix the problem. I also tried increasing the timeout, as well as decreasing the concurrency, but unfortunately the problem still occurs. I have searched Google, as well as the GitHub issues, but have not found anyone mention how to resolve this. Since SQLite is the default when generating a Rails app, I'm surprised this issue hasn't been brought up before. Maybe my jobs are faster or more consistent than other projects?

What can I do to resolve this issue?
