### ISSUE TITLE
brpop is impeding performance

### ISSUE THREAD

**Issue by L-Oto** [mperham/sidekiq#2581]
Hi,

I'm having issues with Redis & Sidekiq. I have to admit that my understanding of the magic between SK & Redis is partial, unfortunately.

My redis server is hosted by RedisCloud. I have one Heroku Standard x1 worker running SK with the following setup:
###### Procfile
````
worker: bundle exec sidekiq -C config/sidekiq.yml -i ${DYNO:-1}
```
###### config.yml
```yaml
:concurrency: 1
staging:
  :concurrency: 4
production:
  :concurrency: 7
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]
```
###### initializers/sidekiq.rb
```ruby
Sidekiq.configure_client do |config|
  config.redis = { size: 2 }
end
```

Here's NewRelic insights on Redis brpop command:
* avg response time: 2s
* min: 4.6ms
* max: 22s
* throughput: 28cpm

It seems that Sidekiq is using the `brpop`command quite a lot!

Is my issue related to an improper configuration of SK and/or Redis or is it a real "issue"?
