### ISSUE TITLE
RedisConnection symbolize_keys can break sentinel support depending on the config hash

### ISSUE THREAD

**Issue by film42** [mperham/sidekiq#3045]
Ruby version: any
Sidekiq / Pro / Enterprise version(s): 4.1.3

This issue is an outline of a breaking change (for us) from 4.1.2 to 4.1.3. We use redis sentinel, which means our redis config is a nested hash. We were previously passing a hash with indifferent access (which is not a very good thing) as our redis config hash. HWIA is deeply indifferently accessible, so redis was able to read the sentinel configs without any issues. Once 4.1.3 started calling `symbolize_keys`, things started to break. We changed our HWIA to `deep_symbolize_keys` and everything was good again.

This is what caused the problem: https://github.com/mperham/sidekiq/commit/8f7943b754dd8f3efba80d3d703272ded032f871#diff-b97259b5fc5f983778f9d492eaa87f9fR11

Here's an example redis config:
```
---
sandbox:
  namespace: my_app
  sentinels:
  - host: sand-sentinel1
    port: 26379
  - host: sand-sentinel2
    port: 26379
  - host: sand-sentinel3
    port: 26379
  url: redis://sand-redis1/
```

I know there isn't an actionable item in this issue, so feel free to close it right away. I just wanted to outline what broke for us in case it offers any value to you guys.

P.S. We love sidekiq! ❤️
