### ISSUE TITLE
Sidekiq Pro - Bundling on CI Server

### ISSUE THREAD

**Issue by ACPK** [mperham/sidekiq#3568]
Ruby version: Sidekiq Pro

The CI server is failing to run "bundle install" due to the need for Sidekiq Pro's auth token.  What would be the best way to provide this every time the CI sets up a new server?

**Comment by mperham** [comment]
The original access email you got upon purchase tells you how to pass the credentials via ENV. Set your CI to include it via ENV.

**Comment by kikocastro** [comment]
This did the trick for me on CircleCI:

1. Gemfile

```yml
    source 'https://gems.contribsys.com/' do
      gem 'sidekiq-pro'
    end
```

2. Define ENV var on CI

```
BUNDLE_GEMS__CONTRIBSYS__COM=<username:password>
```

3. config.yml

```yml
- &install_gems
    name: Install gems and clear not used ones
    command: |
      bundle config --local gems.contribsys.com ${BUNDLE_GEMS__CONTRIBSYS__COM}
      bundle install --clean --path=vendor/bundle --jobs 4 --retry 3
```
