### ISSUE TITLE
wrong queue per namespace

### ISSUE THREAD

**Issue by icotanchev** [mperham/sidekiq#3733]
We have four apps which use a shared Redis cluster with different namespaces. But when we start a BG job it happens(not every time) to create a queue under the wrong redis-namespace which is quite strange. Also, this job stays in status **queued**.

Our setup seems quite standard:

**sidekiq.rb**
```
require 'sidekiq-status'
require 'redis-namespace'

redis_config = YAML.load_file(Rails.root.join('config', 'sidekiq.yml'))[Rails.env]

redis_connection = {
  host: redis_config['host'],
  port: redis_config['port'],
  password: redis_config['password'],
  reconnect_attempts: redis_config['redis_reconnect_attempts'],
  network_timeout: redis_config['redis_timeout'],
  namespace: redis_config['redis_namespace']
}

redis_conn = proc { Redis.new(redis_connection) }

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: redis_config['status_expiration']
  end

  config.redis = ConnectionPool.new(size: 2, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: redis_config['status_expiration']
  end

  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: redis_config['status_expiration']
  end

  config.failures_max_count = redis_config['status_failures_count']

  config.redis = ConnectionPool.new(size: 15, &redis_conn)
end

Sidekiq.default_worker_options = { retry: false }
```

**sidekiq.yml**
```
:verbose: true
:logfile: log/sidekiq.log
:concurrency:  10
:timeout: 30
:queues:
  - <%= `hostname`.strip %>
production:
  host: some_prod_url
  port: 6379
  redis_namespace: admin
  redis_reconnect_attempts: 2
  redis_timeout: 5
  password: SomePassword
  status_failures_count: 5000
  status_expiration: 10.years
development:
  host: 127.0.0.1
  port: 6379
  redis_namespace: admin
  redis_reconnect_attempts: 1
  redis_timeout: 1
  password:
  status_failures_count: 5000
  status_expiration: 10.years
test:
  host: 127.0.0.1
  port: 6379
```

A log file from `kill -TTIN sidekiq_pid_file` can be found [here](https://gist.github.com/icotanchev/d647a5e08aa495be476c69c851c29bbf)

Also, Redis keys contains the wrong namespace + queue 
```
127.0.0.1:6379> keys *
3) "wpf:queue:admin_queue"
```
 
Ruby version: 2.2.2
Rails version: 4.2.7
Sidekiq version: 5.0.5
