### ISSUE TITLE
Sidekiq Enterprise memory leaks

### ISSUE THREAD

**Issue by icotanchev** [mperham/sidekiq#3825]
Ruby version: 2.2.2
Rails version: 4.2.7.1
Sidekiq Enterprise version: 1.7.1

We have purchased an Enterprise license for 400 workers and after the migration to sidekiq we start to experience some memory issues. We have a few long-running(around 20 mins) jobs that export or import data to/from a file and we have noticed that RAM usage on our PROD servers is not released when the job finishes. Also, for a few jobs, we have noticed that they need more than 4 GB of RAM to finish the job they do, which is acceptable in case that this memory will be available after that, but it is not, we have to restart the process after that. The jobs are quite trivial they just export or import data from/to the DB. I guess that this may be related to the ActiveRecord and DB operations but can you advise us.

Our sidekiq initializer is:
```
require 'sidekiq-status'
require 'redis-namespace'

redis_config = YAML.load_file(Rails.root.join('config', 'sidekiq.yml'))[Rails.env]

redis_connection = {
  host: redis_config['host'],
  port: redis_config['port'],
  password: redis_config['password'],
  reconnect_attempts: redis_config['redis_reconnect_attempts'],
  network_timeout: redis_config['redis_timeout'],
  namespace: redis_config['redis_namespace']
}

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: redis_config['status_expiration']
  end

  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: redis_config['status_expiration']
  end

  config.failures_max_count = redis_config['status_failures_count']

  config.redis = redis_connection
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: redis_config['status_expiration']
  end

  config.redis = redis_connection.merge(size: Settings.BackgroundProcessing.CLIENT_POOL_SIZE)
end

Sidekiq.default_worker_options = { retry: false }
```
and the yml file:
```
:verbose: true
:logfile: log/sidekiq.log
:concurrency:  5
:timeout: 30
:queues:
  - <%= `hostname`.strip %>
development:
  host: 127.0.0.1
  port: 6379
  redis_namespace: processing
  redis_reconnect_attempts: 1
  redis_timeout: 1
  password:
  status_failures_count: 5000
  status_expiration: 10.years
test:
  host: 127.0.0.1
  port: 6379
```
