### ISSUE TITLE
Queuing by priority not working as expected

### ISSUE THREAD

**Issue by alpracka** [mperham/sidekiq#3934]
Sidekiq version: 5.2.1 (community)
Ruby version: 2.5.1
Redis version: 3.2.6
OS: Debian 9.5
Rails version: 5.2.1

``` ruby
# sidekiq initializer
redis = { url: 'redis://127.0.0.1:6379/1' }

Sidekiq.configure_client do |config|
  config.redis = redis
end

Sidekiq.configure_server do |config|
  config.redis = redis
end
```

``` yaml
# sidekiq configuration
production:
  :concurrency: 4
staging:
  :concurrency: 1
:queues:
  - mailers
  - default
  - privacy
  - groups
```

Hello,

it seems that queuing by priority is not working as expected.
> This means that any job in the default queue will be processed only when the critical queue is empty.
> - https://github.com/mperham/sidekiq/wiki/Advanced-Options

I see busy threads processing `privacy` queue while there are many jobs queued in `mailers` or `default` queue.  I tried restart, stop/start sidekiq, it processed just a few jobs from a higher priority queue but not all of them and then it started processing `privacy` queue again. Please check attached screenshots.

![image](https://user-images.githubusercontent.com/1401799/44452667-6bddc000-a5f7-11e8-95fd-fc40ea8d8f38.png)
![image](https://user-images.githubusercontent.com/1401799/44452684-77c98200-a5f7-11e8-8cf9-8d06d58a1afa.png)
