### ISSUE TITLE
Sidekiq Enterprise localization

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3949]
Sidekiq Enterprise has localization strings in GEMROOT/web/locales/en.yml.  Non-English customers are welcome to translate that file into their native language so that the Web UI extensions look natural to them.  Here's Sidekiq Enterprise's en.yml:

```
en:
  Limits: Limits
  NoLimitsFound: No limits found
  Size: Size
  Name: Name
  Type: Type
  InUse: In Use
  Loop: Periodic Job
  Loops: Periodic Jobs
  NoLoopsFound: No periodic jobs found
  Schedule: Schedule
  Options: Options
  Held: Held
  HoldTime: Hold Time
  Waited: Waited
  WaitTime: Wait Time
  Overages: Overages
  Reclaimed: Reclaimed
```

Example UI screenshots:

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#web-ui
https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#web-ui

**Comment by hanahiroAze** [comment]
@mperham I'd like to translate, but how can I make pull request to pro/enterprise?
can I add these words to https://github.com/mperham/sidekiq/blob/master/web/locales/en.yml ?

**Comment by mperham** [comment]
Add a comment here with the strings.

**Comment by hanahiroAze** [comment]
here is my idea.

```
ja:
  Limits: 制限
  NoLimitsFound: 同時実行数制限が設定されていません
  Size: サイズ
  Name:  名前
  Type: 種類
  InUse: 使用中
  Loop: 定期実行
  Loops: 定期実行
  NoLoopsFound: 定期実行ジョブがありません
  Schedule: スケジュール
  Options: オプション
  Held: ロック回数
  HoldTime: ロック秒数
  Waited: ロック解放待ち回数
  WaitTime: ロック解放待ち時間
  Overages: タイムアウト超過回数
  Reclaimed: 再ロック要求回数
```

**Comment by mperham** [comment]
thank you, this will go in the next release

**Comment by gustavodiel** [comment]
Hello!

Here are the locations for Brazilian and European Portuguese:
```yaml
pt:
  Limits: Limites
  NoLimitsFound: Nenhum limite encontrado
  Size: Tamanho
  Name: Nome
  Type: Tipo
  InUse: Em uso
  Loop: Tarefa Periódica
  Loops: Tarefas Periódicas
  NoLoopsFound: Nenhuma tarefa periódica encontrada
  Schedule: Cronograma
  Options: Opções
  Held: Bloqueado
  HoldTime: Tempo Bloqueado
  Waited: A Esperar
  WaitTime: Tempo de Espera
  Overages: Invalidez por Idade
  Reclaimed: Bloqueios Recuperados
```

```yaml
pt-br:
  Limits: Limites
  NoLimitsFound: Nenhum limite encontrado
  Size: Tamanho
  Name: Nome
  Type: Tipo
  InUse: Em uso
  Loop: Tarefa Periódica
  Loops: Tarefas Periódicas
  NoLoopsFound: Nenhuma tarefa periódica encontrada
  Schedule: Cronograma
  Options: Opções
  Held: Bloqueado
  HoldTime: Tempo Bloqueado
  Waited: Esperando
  WaitTime: Tempo de Espera
  Overages: Invalidez por Idade
  Reclaimed: Bloqueios Recuperados
```

**Comment by redwarewolf** [comment]
A possible spanish translation.

```
es:
  Limits: Límites
  NoLimitsFound: Ningún Límite Encontrado
  Size: Tamaño
  Name: Nombre
  Type: Tipo
  InUse: En Uso
  Loop: Tarea Periodica
  Loops: Tareas Periodicas
  NoLoopsFound: Ninguna Tarea Periodica Encontrada
  Schedule: Cronograma
  Options: Opciones
  Held: Retenidos
  HoldTime: Tiempo Retenido
  Waited: Esperado
  WaitTime: Tiempo de Espera
  Overages: Exceso
```
  Reclaimed: Reclamado

**Comment by mperham** [comment]
Thank you @redwarewolf, these will be in the next Pro and Ent releases. 😎

**Comment by hanahiroAze** [comment]
@mperham 
The word `Immediate ` looks not translated.
here is my ja version screen.

![2019-03-01 14 09 53](https://user-images.githubusercontent.com/9178166/53617704-bf2a6e00-3c2b-11e9-84b4-226384634137.png)

**Comment by mperham** [comment]
@hakanensari Thank you, I missed this word in en.yml. I've updated the description. The "Immediate" metric shows "Number of times the caller got a concurrent lock immediately, without wait"

**Comment by gustavodiel** [comment]
@mperham do you need a update on the Portugues version with the `Immediate`?

**Comment by mperham** [comment]
Yep, if anyone wants to add Immediate here, I will update the locales so the next version is fixed.

**Comment by gustavodiel** [comment]
For both `pt` and `pt-br` it is:
```yaml
immediate: Imediatos
```

**Comment by mperham** [comment]
thank you!

**Comment by mperham** [comment]
@hakanensari Can you supply a translation so I can update JA and release?

**Comment by hanahiroAze** [comment]
@mperham 

maybe you're making the wrong mention...
it is ja version

```
immediate: 即時ロック取得回数
```

**Comment by fchatterji** [comment]
French:
en:
  Limits: Limites
  NoLimitsFound: Aucune limite trouvée
  Size: Taille
  Name: Nom
  Type: Type
  InUse: En cours d'utilisation
  Loop: Tâche périodique
  Loops: Tâches périodiques
  NoLoopsFound: Aucune tâche périodique trouvée
  Schedule: Programme
  Options: Options
  Held: Bloqué
  HoldTime: Temps de blocage
  Waited: En attente
  WaitTime: Temps d'attente
  Overages: Excédents
  Reclaimed: Récupéré
  Immediate: Immédiat

**Comment by mperham** [comment]
Merci, @fchatterji!

**Comment by loed-idzinga** [comment]
I've made an attempt to translate these terms into Dutch:

```
nl:
  Limits: Limieten
  NoLimitsFound: Geen limieten gevonden
  Size: Grootte
  Name: Naam
  Type: Type
  InUse: In gebruik
  Loop: Periodieke taak
  Loops: Periodieke taken
  NoLoopsFound: Geen periodieke taken gevonden
  Schedule: Tijdsindeling
  Options: Opties
  Held: Vastgehouden
  HoldTime: Tijd vastgehouden
  Waited: In afwachting
  WaitTime: Wachttijd
  Overages: Overschot
  Reclaimed: Teruggewonnen
  Immediate: Onmiddelijk
```

**Comment by davidmetta** [comment]
Italian version:

```YML
it:
  Limits: Limiti
  NoLimitsFound: Nessun Limite trovato
  Size: Quantità
  Name: Nome
  Type: Tipo
  InUse: In Uso
  Loop: Lavoro Periodico
  Loops: Lavori Periodici
  NoLoopsFound: Nessuno Lavoro Periodico trovato
  Schedule: Programma
  Options: Opzioni
  Held: Tenuti
  HoldTime: Tempo di tenuta
  Waited: Attesi
  WaitTime: Tempo di attesa
  Overages: Eccedenze
  Reclaimed: Reclamati
  Immediate: Immediati
```

**Comment by mobilutz** [comment]
Here is a german translation
```
de:
  Limits: Grenzen
  NoLimitsFound: Keine Grenzen gefunden
  Size: Größe
  Name: Name
  Type: Typ
  InUse: In Bearbeitung
  Loop: Periodischer Job
  Loops: Periodische Jobs
  NoLoopsFound: Keine periodischen Jobs gefunden
  Schedule: Pläne
  Options: Optionen
  Held: Einbehalten
  HoldTime: Einbehaltezeit
  Waited: Wartend
  WaitTime: Wartezeit
  Overages: Veraltete
  Reclaimed: Wiedergewonnen
  Immediate: Unmittelbar
```

**Comment by alekgosk** [comment]
polish translation:

```yml
pl:
  Limits: Limity
  NoLimitsFound: Nie znaleziono limitòw
  Size: Rozmiar
  Name: Nazwa
  Type: Typ
  InUse: W użyciu
  Loop: Okresowe zadanie
  Loops: Okresowe zadania
  NoLoopsFound: Nie znaleziono okresowych zadań
  Schedule: Harmonogram
  Options: Opcje
  Held: Zachowane
  HoldTime: Czas blokowania
  Waited: Czekanie
  WaitTime: Czas oczekiwania
  Overages: Nadwyżki
  Reclaimed: Odzyskano
  Immediate: Natychmiastowy
```

**Comment by mperham** [comment]
👍🏼😎

**Comment by ogom** [comment]
Added `Periodic` to Japanese

```yaml
ja:
  Limits: 制限
  NoLimitsFound: 同時実行数制限が設定されていません
  Size: サイズ
  Name: 名前
  Type: 種類
  InUse: 使用中
  Loop: 定期実行
  Loops: 定期実行
  Periodic: 定期実行
  NoLoopsFound: 定期実行ジョブがありません
  Schedule: スケジュール
  Options: オプション
  Held: ロック回数
  HoldTime: ロック秒数
  Waited: ロック解放待ち回数
  WaitTime: ロック解放待ち時間
  Overages: タイムアウト超過回数
  Reclaimed: 再ロック要求回数
  Immediate: 即時ロック取得回数
```

**Comment by gunnner** [comment]
Hello, here's Ukrainian verion:

```yaml
uk:
  Limits: Ліміти
  NoLimitsFound: Обмежень не знайдено
  Size: Розмір
  Name: Назва
  Type: Тип
  InUse: У використанні
  Loop: Періодичне завдання
  Loops: Періодичні завдання
  NoLoopsFound: Періодичних завдань не знайдено
  Schedule: Розклад
  Options: Параметри
  Held: Затримано
  HoldTime: Час затримки
  Waited: Очікувань
  WaitTime: Час очікування
  Overages: Перевищення
  Reclaimed: Звільнено
  Immediate: Без очікування
```
