### ISSUE TITLE
Sidekiq Pro localization

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3951]
Sidekiq Pro only has localization for English today.  I'd like to fix that if possible.  Here's the English strings file if you'd like to translate it to another language so that Pro's Web UI will look more natural in that language.

```
en:
  Batch: Batch %{bid}
  Batches: Batches
  NoBatchesFound: No batches found
  Description: Description
  Size: Size
  Pending: Pending
  Job: Job
  Class: Class
  Failures: Failures
  ErrorMessage: Error Message
  ErrorBacktrace: Error Backtrace
  Started: Started
  JobCount: Job Count
  Failed: Failed
  Status: Status
  Parent: Parent
```

Here's the Web UI in context.

<img width="700" alt="screen shot 2018-09-06 at 9 25 07 am" src="https://user-images.githubusercontent.com/2911/45171312-e6413f00-b1b6-11e8-9b1e-51695e47715a.png">

<img width="611" alt="screen shot 2018-09-06 at 9 25 25 am" src="https://user-images.githubusercontent.com/2911/45171314-e8a39900-b1b6-11e8-892e-73dd8e7821e6.png">

**Comment by hanahiroAze** [comment]
here is my idea

```
ja:
  Batch: バッチ %{bid}
  Batches: バッチ処理
  NoBatchesFound: バッチ処理が設定されていません
  Description: 説明
  Size: サイズ
  Pending: 未成功
  Job: ジョブ
  Class: クラス
  Failures: 失敗
  ErrorMessage: エラーメッセージ
  ErrorBacktrace: バックトレース
  Started: 開始
  JobCount: 回数
  Failed: 失敗
  Status: ステータス
  Parent: 親
```

**Comment by mperham** [comment]
Leaving it open for other languages.

**Comment by zharikovpro** [comment]
```
ru:
  Batch: Партия %{bid}
  Batches: Партии
  NoBatchesFound: Партии не найдены
  Description: Описание
  Size: Размер
  Pending: Ожидает
  Job: Задача
  Class: Класс
  Failures: Провалы
  ErrorMessage: Сообщение об ошибке
  ErrorBacktrace: Трассировка ошибки
  Started: Начато
  JobCount: Число задач
  Failed: Провалено
  Status: Статус
  Parent: Родитель
```

**Comment by mperham** [comment]
Thank you so much Andrey, Russian will be in 4.0.5.

**Comment by gustavodiel** [comment]
Hello!

Here are the locales for Portuguese and Brazilian Portuguese

```yaml
pt:
  Batch: Lote %{bid}
  Batches: Lotes
  NoBatchesFound: Nenhum lote encontrado
  Description: Descrição
  Size: Tamanho
  Pending: Aguardando
  Job: Tarefa
  Class: Classe
  Failures: Falhas
  ErrorMessage: Mensagem de Erro
  ErrorBacktrace: Backtrace do Erro
  Started: Iniciados
  JobCount: Quantidade de Tarefas
  Failed: Falhas
  Status: Estado
  Parent: Pai
```

```yaml
pt-br:
  Batch: Lote %{bid}
  Batches: Lotes
  NoBatchesFound: Nenhum lote encontrado
  Description: Descrição
  Size: Tamanho
  Pending: Aguardando
  Job: Tarefa
  Class: Classe
  Failures: Falhas
  ErrorMessage: Mensagem de Erro
  ErrorBacktrace: Backtrace do Erro
  Started: Iniciados
  JobCount: Quantidade de Tarefas
  Failed: Falhas
  Status: Estado
  Parent: Pai
```

**Comment by mperham** [comment]
Thank you so much, I will get this in the next version. There is an Enterprise issue too if you want to do the same there.

**Comment by mperham** [comment]
@Lihua93 Thank you!

**Comment by rfkdali** [comment]
```yml
fr:
  Batch: Lot %{bid}
  Batches: Lots
  NoBatchesFound: Lots non trouvés
  Description: Description
  Size: Taille
  Pending: En attente
  Job: Tâche
  Class: Classe
  Failures: Échecs
  ErrorMessage: Message d'erreur
  ErrorBacktrace: Erreur Backtrace
  Started: Commencé
  JobCount: Nombre de tâches
  Failed: Échoué
  Status: Statut
  Parent: Parent
```

**Comment by mperham** [comment]
@rfkdali Merci!

**Comment by ThomasKoppensteiner** [comment]
@mperham you may find https://lingohub.com/ useful for managing the translations.

**Comment by redwarewolf** [comment]
Here is a possible spanish translation.

```
es:
  Batch: Lote %{bid}
  Batches: Lotes
  NoBatchesFound: Ningún lote ha sido encontrado
  Description: Descripción
  Size: Tamaño
  Pending: Pendiente
  Job: Tarea
  Class: Clase
  Failures: Fallidos
  ErrorMessage: Mensaje de Error
  ErrorBacktrace: Seguimiento de Error
  Started: Comenzado
  JobCount: Cantidad de Tareas
  Failed: Fallido
  Status: Estado
  Parent: Parent
```

**Comment by balakirevs** [comment]
Ukrainian one:

```
ua:
  Batch: Партія %{bid}
  Batches: Партії
  NoBatchesFound: Партії не знайдені
  Description: Опис
  Size: Розмір
  Pending: Чекає
  Job: Завдання
  Class: Клас
  Failures: Невдачі
  ErrorMessage: Повідомлення про помилку
  ErrorBacktrace: Трасування помилки
  Started: Розпочато
  JobCount: Число завдань
  Failed: Невдалі
  Status: Статус
  Parent: Батько
```

**Comment by mperham** [comment]
@balakirevs This is great but Sidekiq itself doesn't have a Ukrainian locale, most of the UI will still be in English. We need a ua.yml here too if you want to provide one: https://github.com/mperham/sidekiq/tree/master/web/locales

**Comment by loed-idzinga** [comment]
Thank you for your awesome work @mperham, here are the Dutch translations. Not entirely sure about the `parent` though. In what context is it used? I don't see it anywhere in the interface.

```
nl:
  Batch: Groep %{bid}
  Batches: Groepen
  NoBatchesFound: Geen groepen gevonden
  Description: Omschrijving
  Size: Grootte
  Pending: In afwachting
  Job: Taak
  Class: Klasse
  Failures: Mislukkingen
  ErrorMessage: Foutmelding
  ErrorBacktrace: Fout backtrace
  Started: Gestart
  JobCount: Aantal taken
  Failed: Mislukt
  Status: Status
  Parent: Bovenliggende
```

**Comment by mperham** [comment]
Thanks Loed, "Parent" is the parent batch ID.  It's used in the sense of a parent and child node in a tree structure. I will integrate these as is, let me know if anything needs to change.

**Comment by davidmetta** [comment]
Italian version:

```YML
it:
  Batch: Lotto %{bid}
  Batches: Lotti
  NoBatchesFound: Nessun Lotto trovato
  Description: Descrizione
  Size: Dimensione
  Pending: In attesa
  Job: Lavoro
  Class: Classe
  Failures: Fallimenti
  ErrorMessage: Messagio di errore
  ErrorBacktrace: Backtrace dell'errore
  Started: Iniziato
  JobCount: Numero di lavori
  Failed: Fallito
  Status: Stato
  Parent: Genitore
```

**Comment by mperham** [comment]
@davidmetta Thank you so much, this will be in the next Pro release. If you want to translate Enterprise, you can find the strings here:

https://github.com/mperham/sidekiq/issues/3949#issue-357717719

**Comment by delphaber** [comment]
Updated italian version:

```
it:
  Batch: Batch %{bid}
  Batches: Batch
  NoBatchesFound: Nessun batch trovato
  Description: Descrizione
  Size: Dimensione
  Pending: In attesa
  Job: Job
  Class: Classe
  Failures: Fallimenti
  ErrorMessage: Messagio di errore
  ErrorBacktrace: Backtrace dell'errore
  Started: Iniziato
  JobCount: Numero di job
  Failed: Fallito
  Status: Stato
  Parent: Genitore
  DeadJIDs: JID arrestati
  PendingJIDs: JID in attesa
```

**Comment by tisba** [comment]
Not using Pro, but a German native speaker and like to contribute :)

* "batch" could be translated, but I'm not sure what works best. Assume some technical background "Batch" works fine in German.
* According to https://github.com/mperham/sidekiq/blob/main/web/locales/de.yml "Job" wasn't translated either, which is also would I would have done. ✅ 
* "Parent" could be "Eltern", but I would need to see that in context (I know that this is about parent-child relationships).

```yaml
de:
  Batch: Batch %{bid}
  Batches: Batches
  NoBatchesFound: Kein Batch gefunden
  Description: Beschreibung
  Size: Größe
  Pending: Bevorstehend
  Job: Job
  Class: Klasse
  Failures: Fehler
  ErrorMessage: Fehlermeldung
  ErrorBacktrace: Fehlerprotokoll
  Started: Gestartet
  JobCount: Job Anzahl
  Failed: Fehlgeschlagen
  Status: Status
  Parent: Parent
```
