### ISSUE TITLE
Dark mode web UI?

### ISSUE THREAD

**Issue by silent-e** [mperham/sidekiq#4227]
Not an issue, just curious.  Has anyone written custom CSS to change the WebUI to a dark mode?  I hacked together something real quick and I'm using it with the Stylish extension.  It's ugly and not complete but it a start and gets the job done for now.

(e)

```css
body {
  background-color: #111;
  color: #fff;
}

table.table-white {
  background-color: hsl(0, 0%, 21%);
}

.table-striped > tbody > tr:nth-of-type(odd) {
  background-color: hsl(0, 0%, 13%);
}

.table-bordered,
.table-bordered > tbody > tr > td,
.table-bordered > tbody > tr > th,
.table-bordered > tfoot > tr > td,
.table-bordered > tfoot > tr > th,
.table-bordered > thead > tr > td,
.table-bordered > thead > tr > th {
  border: 1px solid hsl(0, 0%, 24%);
}

.table-hover > tbody > tr:hover {
  background-color: hsl(217, 24%, 34%);
}

a:link,
a:active,
a:hover,
a:visited {
  color: hsl(208, 49%, 55%);
}

.summary_bar ul .count {
  color: hsl(200, 49%, 38%);
}

.summary_bar .summary {
  background-color: hsl(0, 0%, 16%);
}

.navbar-default {
  background-color: hsl(0, 0%, 13%);
  border-color: hsl(0, 0%, 24%);
}

.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:focus,
.navbar-default .navbar-nav > .active > a:hover {
  color: hsl(0, 0%, 100%);
  background-color: hsl(0, 0%, 16%);
}

.pagination > li > a,
.pagination > li > span {
  color: hsl(0, 0%, 100%);
  background-color: hsl(0, 0%, 16%);
  border-color: hsl(0, 0%, 21%);
}
.pagination > .disabled > a,
.pagination > .disabled > a:focus,
.pagination > .disabled > a:hover,
.pagination > .disabled > span,
.pagination > .disabled > span:focus,
.pagination > .disabled > span:hover {
  color: hsl(0, 0%, 65%);
  background-color: hsl(0, 0%, 16%);
  border-color: hsl(0, 0%, 21%);
}

.stat {
  border: 1px solid hsla(0, 0%, 100%, 0.1);
}
```
