### ISSUE TITLE
Rails 6 ActiveRecord manual connection switching broken in Sidekiq workers

### ISSUE THREAD

**Issue by kpheasey** [mperham/sidekiq#4380]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 5.0.3

Receiving  `ActiveRecord::ConnectionNotEstablished` shortly after starting sidekiq process.  It looks like I can process 20 jobs, then it just can't process anymore.  I assume that means the connections are not being returned to the pool, but I'm not sure where to start looking in Sidekiq.

If it matters, the connection is not related to a model.  It's just another database we use and only connect to within a sidekiq worker.

```
ActiveRecord::ConnectionNotEstablished: No connection pool with 'primary' found.
```

```
# database.yml

database: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: 20

etl:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['OTHER_DB_NAME'] %>
  username: <%= ENV['OTHER_DB_USERNAME'] %>
  password: <%= ENV['OTHER_DB_PASSWORD'] %>
  host: <%= ENV['OTHER_DB_HOST'] %>
  port: <%= ENV['OTHER_DB_PORT'] %>
  pool: 20
```

```
# sidekiq.yml

:verbose: true
:concurrency:  15
:timeout: 10
:queues:
  - default
  - mailers
```

```
# app/workers/worker.rb

class SourceDataImportWorker
  include Sidekiq::Worker

  def perform(etl_job_id, adapter, key)
    return unless (etl_job = EtlJob.find_by(id: etl_job_id))
    etl_job.active!

    ActiveRecord::Base.connected_to(database: :etl) do
      S3CsvImport.new(...).perform
    end
  end
end
```
