### ISSUE TITLE
running Sidekiq on Azure

### ISSUE THREAD

**Issue by RomainFranklin** [mperham/sidekiq#4648]
Ruby version: 2.6.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.3

I have a Ruby on Rails application with Sidekiq. I run it on Heroku for years with web dynos for the web server and worker dynos for Sidekiq (https://devcenter.heroku.com/articles/background-jobs-queueing).

I managed to make the web server work on Azure, quite simply.

I now have trouble trying to make Sidekiq work on Azure. The concept of workers (as defined by Heroku) does not seem to exist on Azure.

Here is what I've done so far:
- I tried to configure a web app for container with the following start command: bundle exec sidekiq -C config/sidekiq.yml
  - sidekiq starts but as the container cannot handle the HTTP ping (health check) from Azure (as sidekiq is not a web server), the container is automatically shut down (Container didn't respond to HTTP pings on port: XXXX)
  - there is no option to deactivate the HTTP ping => https://docs.microsoft.com/fr-fr/archive/blogs/waws/things-you-should-know-web-apps-and-linux#your-container-must-respond-to-an-http-pingapplies-to-web-app-for-containers

- I tried to configure a web app with docker-compose:
```
version: "3.7"
services:
  web:
    image: "myregistry.azurecr.io/myimage:latest"
    ports:
      - 80:80
  sidekiq:
    image: "myregistry.azurecr.io/myimage:latest"
    command: bundle exec sidekiq -C config/sidekiq.yml
```
=> both services (web + sidekiq) start correctly, but after a few minutes, I have the following error: ERROR - multi-container unit was not started successfully without more details.

- I finally tried to configure a container instance: https://azure.microsoft.com/fr-fr/services/container-instances/ => I have no idea how to execute sidekiq once the container is up

Does anyone has managed to make sidekiq work on Azure? Thank you!
