### ISSUE TITLE
Jobs randomly stuck for a long time

### ISSUE THREAD

**Issue by jacek213** [mperham/sidekiq#4699]
Ruby version: 2.6.5 (jemalloc)
Rails version: 5.1.7
Sidekiq / Pro / Enterprise version(s): 5.2.9
Server: Redhat Enterprise 7.8

**sidekiq.yml**

```yaml
---
development:
  :verbose: true
  :concurrency: 5
production:
  :logfile: ./log/sidekiq.log
  :concurrency: 8
:pidfile: ./tmp/pids/sidekiq.pid
:queues:
  - default
  - asc_import
  - asc_import_equipment
  - mailers
  - renders_download
:schedule:
  clear_shrine_cache:
    cron: '00 01 * * *'
    class: ShrineCacheWorker
  check_stale_car_models:
    cron: '00 8,20 * * *'
    class: StaleCarModelsWorker
```

**Initializer**

```ruby
Sidekiq.configure_server do |config|
  config.redis = MockRedis.new if Rails.env.test?

  config.error_handlers << Proc.new do |ex, ctx_hash|
    ExceptionNotifier.notify_exception(ex)
  end
end

```

On my production server some jobs get stuck for amount of time which is usually in range of 1min to 60mins. From my observations, it happens to workers which make external HTTP calls. It's not an easy thing to debug because it happens randomly. However, it happens pretty often. Also, I have no idea what's actually going on during that time.

In the web panel I just see the job as **busy**. It always succeeds, however it takes a lot of time. External requests are made using Faraday (0.15.3).

![sidekiq-panel](https://user-images.githubusercontent.com/3914691/94021082-ec151780-fdb3-11ea-9015-931ccade3ecb.jpg)

**Example worker:**

```ruby
# frozen_string_literal: true

class WlsGenericLeadsWorker
  include Sidekiq::Worker
  sidekiq_options queue: :default, retry: 5, backtrace: true

  def perform(generic_lead_form_id)
    generic_lead_form = GenericLeadForm.find(generic_lead_form_id)
    payload = Wls::GenericLeadPayload.new(generic_lead_form)
    sender = Wls::Sender.new(payload)
    sender.call
  end
end

```

It just fetches a record from database by ID, prepares payload based on it's data and sends a POST request with Faraday. It happens for other workers as well.

**The log**

![log-sidekiq](https://user-images.githubusercontent.com/3914691/94022016-f257c380-fdb4-11ea-9576-fc384a971498.jpg)

As you can see, the job was started at 13:06 and the actual request was made at 13:21. What happened in between remains unknown.

**Appsignal panel**

![appsignal-screen](https://user-images.githubusercontent.com/3914691/94023971-20d69e00-fdb7-11ea-8037-89ed893cc321.jpg)

Here's also a screen from appsignal panel. As you can see CPU Usage is low and there's more than plenty of memory and swap.

**Timeline**

![image](https://user-images.githubusercontent.com/3914691/94025368-b6bef880-fdb8-11ea-9037-143642c57ab8.png)

The timeline indicates that `activerecord` and `net_http` were called at the very end and the job had been stuck at `sidekiq` itself for 15 minutes.

Puma server working on the same machine causes no problems and handles around 500 requests a minute.

Help would be more than welcome... I've been struggling with that for quite some time.
