### ISSUE TITLE
Combine TSTP and TERM into a seperate Signal

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [mperham/sidekiq#4822]
Right now I try to implement a gracefull shutdown command/script for our kubernetes cluster - our pod/worker should get a signal to quiet it's job consumption and exit after but still should continue with the existing taken jobs (but only up to a specific time limit).

It would be cool if you offer a new signal, which combines the quiet and term signals, so we don't have to create a custom script for it?

Or maybe add an option like 
```ruby
Sidekiq.configure_server do |config|
   config.exit_after_quiet_and_empty_jobs = true
   config.quiet_exit_timeout = 600
end

```
This would allow us to just send TSTP to our process, and it shuts down completely gracefully within a specific timeframe.. Right now we have to figure out if the workers are finished with processing and send the TERM signal by ourselfes?

Hope I didn't miss anything!

Also the current workarounds are pretty big scripts or complicated..

See here:
https://blog.cloud66.com/kubernetes-sidekiq-shutdown/

Following works, but waits for TERM unnecessary long:
https://github.com/arturictus/sidekiq_alive#sidekiq--6-1

Would love to hear your feedback!

**Comment by mperham** [comment]
You don't need TSTP at all.

> bundle exec sidekiq -t 600

Will wait up to 600 seconds for jobs to finish after TERM.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hmmm.. Somehow it doesn't work for me, it just launches a new sidekiq worker when I run this command?
Or shall I just start my workers with the -t command and just send TERM?

**Comment by mperham** [comment]
Yes, I believe -t is what you want.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you very much @mperham !

I got it working with following kubernetes configuration - it waits not for the workers to complete their work (up to 20 minutes) and then shuts it down. Not sure why I have to add the preStop-hook, but it seems that the TERM signal doesn't get sent before the terminationGracePeriodSeconds. But anyway -> following works nicely:

```yaml
    spec:
      terminationGracePeriodSeconds: 1200
      containers:
        - name: mysidekiq
          command: ["/bin/sh","-c", "bundle exec sidekiq -t 1200"] 
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c", "kill -TERM $(ps aux | grep sidekiq | grep busy | awk '{ print $2 }')"] 

```
