### ISSUE TITLE
sidekiq_options being ignored when worker is inside 3rd party gem

### ISSUE THREAD

**Issue by Daltron** [mperham/sidekiq#4842]
Ruby version: 2.6.1
Rails version: 6.0
Sidekiq / Pro / Enterprise version(s): 6.1.1

I created a gem that is simply responsible for creating a single sidekiq worker. However `sidekiq_options` seems to be getting ignored for some reason. All of my other workers that are directly inside my root project have no issues with `sidekiq_options` being detected. Any ideas on what might be going on?

```yml
# sidekiq.yml
backup_database:
  cron: "0 3 * * *"
  class: "SafetyNetHeroku::BackupDatabaseWorker"
```
```ruby
# backup_database_worker.rb
module SafetyNetHeroku
  class BackupDatabaseWorker
    include Sidekiq::Worker

    sidekiq_options retry: false

    def perform
    end

  end
end
```

<img width="844" alt="Screen Shot 2021-03-13 at 9 56 40 PM" src="https://user-images.githubusercontent.com/9689335/111056733-0d8fbb80-8447-11eb-8eb6-c00c9b1fe36a.png">
