### ISSUE TITLE
Multiple sidekiq queues on different cores(processes)

### ISSUE THREAD

**Issue by abhinav-94** [mperham/sidekiq#4844]
gem 'sidekiq', '6.0.4'
gem 'rails', '5.1.1'
ruby:2.5.0

I want to run multiple sidekiq queues and i want to utilise the multiple cores, so i want different queues to run different cores. I tried do the following in my cmd and args section in the YAML file.

```
apiVersion: apps/v1         
kind: Deployment
metadata:
  name: sidekiq-workers
  namespace: sidekiq-jobs
  labels:
    app: background-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background-jobs
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: background-jobs
    spec:
      containers:
        - name: background-jobs
          image: **********some_remote_repo**********
          command: ["/bin/sh","-c"]
          args: ["bundle exec sidekiq -c 25 -q update_prices,5; bundle exec sidekiq -c 25 -q update_inventory,10"]
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 3000
          resources:
            limits:
              cpu: '10'
              memory: 50Gi
            requests:
              cpu: '1'
              memory: 10Gi
                
```

Problem here is that only one sidekiq queue is getting started, the second one. 
If i give the below arguments, then both the queues start but on the same processor. So multiple cores are not being used.
```
args: ["bundle exec sidekiq -c 25 -q update_prices,5 -q update_inventory,10"]
```

Here is one more way i tried
```
          args:
            - bundle exec sidekiq -e production -C config/sidekiq.yml;
            - bundle exec sidekiq -e production -C config/sidekiq2.yml;
```

With the sidekiq files being

sidekiq.yml
```
:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - update_prices
 
production:
  :concurrency: 25
development:
  :concurrency: 15
```

sidekiq2.yml
```
:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - update_inventory
 
production:
  :concurrency: 25
development:
  :concurrency: 15
```

Is it possible to do this, i.e. to run sidekiq queues on different cores. I am on MRI interpretation of Ruby.
If yes, then how? Let me know if more information is required.

**Comment by mperham** [comment]
It sounds like you need help from your deployment platform. I don’t know the tool you are using so I can’t help.

**Comment by 0x0badc0de** [comment]
Just create one more container:
```
      containers:
        - name: background-jobs1
          command: ["bundle", "exec", "sidekiq", "-c", "25", "-q", "update_prices,5"]
          ...
        - name: background-jobs2
          command: ["bundle", "exec", "sidekiq", "-c", "25", "-q", "update_inventory,10"]
          ...
```
