### ISSUE TITLE
[Question] How can I display all jobs defined in multiple ProcessSets in the Recurring Jobs tab of the Sidekiq Web UI.

### ISSUE THREAD

**Issue by ayemohmohthu** [mperham/sidekiq#5148]
Ruby version: 2.4.1
Rails version: 5.1.6.1
Sidekiq version: 5.2.3
Docker version: 3

Hi Mike,
I prepared multiple Sidekiq servers to create multiple ProcessSets in my application.
But only Jobs of one ProcessSet are displayed in the Recurring Jobs of the Sidekiq Web UI. 
However Jobs defined on the other ProcessSet are not displayed in the Recurring Jobs, but I could run those jobs from application. 
What should I do to display the Jobs defined in all ProcessSets in the Recurring Jobs of the Sidekiq web UI?

docker-compose.yml
```
  sidekiq:
    <<: *app_base
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    ports: []
    depends_on: []
    tty: false
    stdin_open: false
  
  sidekiq_for_heavy:
    <<: *app_base
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq_for_heavy.yml"]
    ports: []
    depends_on: []
    tty: false
    stdin_open: false
```
config/sidekiq.yml
```
:verbose: false
:pidfile: ./tmp/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 10
:queues:
  - default
  - low_priority
:limits:
  default: 5
  low_priority: 5
:schedule:
  test:
    cron: "0 * * * * *" # 毎分0秒
    class: SampleWorker
```
sidekiq_for_heavy.yml
```
:verbose: false
:pidfile: ./tmp/sidekiq_for_heavy.pid
:logfile: ./log/sidekiq_for_heavy.log
:concurrency: 10
:queues:
  - high_priority
  - default
:limits:
  high_priority: 3
  default: 3
:schedule:
  test-heavy:
    cron: "0 30 8 1 * *" # 毎分0秒
    class: SampleWorkerForHeavy
```

initializer
```
class MySidekiqFormatter < Sidekiq::Logging::WithoutTimestamp

  require 'sidekiq/web'
  require "sidekiq/pro/web"
  Sidekiq::Web.set :sessions, false

  def call(severity, time, program_name, message)
    "#{time.localtime.iso8601(3)} #{super}"
  end
end

Sidekiq.configure_server do |config|
  Sidekiq::Logging.logger.formatter = MySidekiqFormatter.new
  config.redis = { url: "redis://" + ENV.fetch("REDIS_HOST", "redis") + ":" + ENV.fetch("REDIS_PORT", "6379")}
end

Sidekiq.configure_client do |config|
  Sidekiq::Logging.logger.formatter = MySidekiqFormatter.new
  config.redis = { url: "redis://" + ENV.fetch("REDIS_HOST", "redis") + ":" + ENV.fetch("REDIS_PORT", "6379")}
end

```
