### ISSUE TITLE
Dark mode for disabled cron jobs is unreadable

### ISSUE THREAD

**Issue by JoshCheek** [mperham/sidekiq#5241]
Ruby version: 3.1
Rails version: 6.1
Sidekiq version: 6.4.0 (current version is 6.4.1, and I did check the changelog to verify this wasn't fixed)

IDK why, but Sidekiq is using dark mode. I don't really care either way, except that I can't read the white on pink of the disabled cron jobs. I saw several issues asking how to turn dark mode off, but didn't see anything there or in the docs. I know it's OSS and I could go fix it, but I'm extremely novice at CSS and I'm not a designer. I can see that the background-color is probably for light mode, and could probably figure out where that's coming from, but IDK what it should be.

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/77495/157912812-d43b9060-2d43-40bf-adda-f2b3a69cee52.png">

**config/chedule.yml**
```yaml
this_one_is_enabled:
  # "At 15:00 ET on Tuesday."
  cron: "0 15 * * 2 America/New_York"
  class: "ThisOneIsEnabled"
  queue: default
  active_job: true
  description: "I enabled this job"

this_one_is_disabled:
  # "At 09:00 on every day-of-week from Monday through Friday"
  cron:        '0 9 * * 1-5 America/New_York'
  class:       "ThisOneIsDisabled"
  queue:       default
  active_job:  true
  description: "I disabled this job"
```

**config/sidekiq.yml**
```yaml
# Concurrency prod value taken from https://manuelvanrijn.nl/sidekiq-heroku-redis-calc/
# Redis connections = 20 # this is our Redis plan's total allowed connections.
# web_dynos         = 1
# web_threads       = 5 (Using puma with 5 threads)
# client_conn       = 1  (each web process thread makes to the Redis server)
# worker_dynos      = 1  (1 worker running the sidekiq process)

:concurrency: 5

staging:
  :concurrency: 5
production:
  :concurrency: 13
:queues:
  - default                     # We specify this one in our jobs
  - mailers                     # ActionMailer::Base.deliver_later_queue_name
  - action_mailbox_routing      # ActionMailbox.queues[:routing]
  - action_mailbox_incineration # ActionMailbox.queues[:incineration]
  - active_storage_analysis     # ActiveStorage.queues[:analysis]
  - active_storage_purge        # ActiveStorage.queues[:purge]
```

**config/initializers/sidekiq.rb**
```ruby
Sidekiq.configure_server do |config|
  config.redis = {
    url: ENV['REDIS_URL'],
    network_timeout: 5,
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
  }
  schedule_file = "config/schedule.yml"

  if Sidekiq.server?
    ActiveSupport.on_load :after_initialize do
      Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
    end
  end
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV['REDIS_URL'],
    network_timeout: 5,
    size: 1,
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
  }
end
```
