### ISSUE TITLE
sidekiq worker not sending emails

### ISSUE THREAD

**Issue by MarcosRodas24** [mperham/sidekiq#5447]
Ruby version:2.7.4
Rails version:5.0.7.2
Sidekiq / Pro / Enterprise version(s): 5.1.1

I have the following  sidekiq job

```
class InternalDailyStatusMailWorker
  include Sidekiq::Worker
  include WorkerErrorHandling

  sidekiq_options retry: false,
                  queue: 'notifications_internal',
                  lock: :until_and_while_executing,
                  run_lock_expiration: 60 * 60 # 1 hour

  def perform_with_error_handling
    AdminNotifier.daily_status.deliver_now if Feature[:daily_status_emails].enabled?
  end
end


```
and it is added in sidekiq cron like this:
```

daily_status_email:
   cron:  "0 6 * * * America/New_York"
   class: InternalDailyStatusMailWorker
   queue: notifications_internal
```

the worker is supposed to send emails but it never does  when I run the notifier from rails console it sends the mails correctly
