### ISSUE TITLE
sidekiq 6.5.7 stopped processing jobs on our app

### ISSUE THREAD

**Issue by michelson** [mperham/sidekiq#5602]
Ruby version: 2.7
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): Sidekiq

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```yaml
---
  :concurrency: 2
  staging:
    :concurrency: 5
  production:
    :concurrency: 5
  :queues:
    - [mailers, 2]
    - [default, 1]
    - [active_storage_analysis, 2]
    - [active_storage_purge, 2]
```

**problem**: I'm planning to upgrade to sidekiq 7 so I've just updated from 6.4.1 to 6.5.7, but suddenly the processing stopped and we had to downgrade again to 6.4.1 and it started the processing.
