### ISSUE TITLE
Please point Sidekiq to a Rails application or a Ruby file to load your job classes with -r [DIR|FILE].

### ISSUE THREAD

**Issue by KoeusIss** [mperham/sidekiq#5727]
Ruby version: 2.7.5
Rails version: 6.1.6
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
### config/initializers/sidekiq.rb
```
Sidekiq.configure_server do |config|
  redis_url = ENV.fetch("REDIS_HOST", "localhost")
  redis_port = ENV.fetch("REDIS_PORT", 6379)
  redis_password = ENV.fetch("REDIS_PASSWORD", "")

  config.redis = { url: "redis://#{redis_url}:#{redis_port}", password: redis_password }
end

Sidekiq.configure_client do |config|
  redis_url = ENV.fetch("REDIS_HOST", "localhost")
  redis_port = ENV.fetch("REDIS_PORT", 6379)
  redis_password = ENV.fetch("REDIS_PASSWORD", "")

  config.redis = { url: "redis://#{redis_url}:#{redis_port}", password: redis_password }
end
```
### sidekiq.yml
```
:timeout: 80
:concurrency: 10
:verbose: false
:queues:
  - my_queue
```
### kubernetes deployment
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my_namespace
  name: application-sidekiq
  labels:
    app.kubernetes.io/name: application-sidekiq
    workload-type: sidekiq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: application-sidekiq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: application-sidekiq
    spec:
      containers:
        - name: application-sidekiq
          image: my_registry
          imagePullPolicy: Always
          command:
            - bundle
          args:
            - exec
            - sidekiq
            - "-C"
            - "/app/config/sidekiq.yml"
          resources:
            requests:
              cpu: ...
              memory:  ...
            limits:
              cpu: ...
              memory: ...
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-sidekiq
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-sidekiq
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-sidekiq
                  key: REDIS_PASSWORD
          volumeMounts:
            - mountPath: /app/config
              name: sidekiq-yml
      volumes:
        - name: sidekiq-yml
          configMap:
            name: sidekiq-yml
            items:
            - key: sidekiq.yml
              path: sidekiq.yml
```
### Error:
```
==================================================================
  Please point Sidekiq to a Rails application or a Ruby file  
  to load your job classes with -r [DIR|FILE].
==================================================================
```
If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md
