### ISSUE TITLE
Sidekiq Connection Pooling issues with Read Replica on Rails 6.1

### ISSUE THREAD

**Issue by KidA001** [mperham/sidekiq#5778]
Ruby version: 3.1.2
Rails version: 6.1.6
Sidekiq: 6.4.2

We recently implemented a read-replica in our Rails 6 application. We are only using it for specific transactions by wrapping them in a block like so:
```ruby
ActiveRecord::Base.connected_to(role: :reading) do
  # read query here
end
```

When this code is being executed from a Sidekiq job, we get the following error:
```
ActiveRecord::ConnectionTimeoutError in [NameOfJob # perform]
ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.058 seconds); all pooled connections were in use
```

Based on all the documentation I've read for Rails 6 using multiple DB's, connection pooling is managed by what is set in your `database.yaml`. This is what we have:

```yaml
production:
  primary:
    url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
    reaping_frequency: <%= ENV["REAPING_FREQUENCY"] || 10 %>
    adapter: postgresql
    advisory_locks: false
  primary_replica:
    url: <%= ENV['REPLICA_DATABASE_POOL_URL'] || ENV['DATABASE_URL'] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
    reaping_frequency: <%= ENV["REAPING_FREQUENCY"] || 10 %>
    adapter: postgresql
    advisory_locks: false
    replica: true
```
RAILS_MAX_THREADS is set to 12 and REAPING_FREQUENCY is set to 10 on our environment.

In our `Procfile` we are starting our default queue with: `sidekiq -c ${SIDEKIQ_RAILS_CONCURRENCY:-6} -q default` and `SIDEKIQ_RAILS_CONCURRENCY` is set to 12 in our Environment

I cannot replicate this behavior in our mirrored development environments even if I queue up a bunch of jobs and workers to process them. I'm at a loss on what I am missing with our connection pooling config. Most of the documentation I've read for rails 6 says we don't need to set any specific config for pooling in sidekiq.rb or puma.rb. But I also don't see any specific instruction for managing this for a replica.

`sidekiq.rb`:
```ruby
# frozen_string_literal: true

# if Rails.env.production? || Rails.env.staging?
Sidekiq.configure_client do |config|
  Rails.application.config.after_initialize do
    ActiveSupport.on_load(:active_record) do
      ActiveRecord::Base.connection_pool.enable_query_cache!
    end
  end

  config.redis = { url: ENV['REDIS_URL'] }
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'], reconnect_attempts: 1 }

  config.death_handlers << lambda { |job, _ex|
    SidekiqUniqueJobs::Digests.del(digest: job['unique_digest']) if job['unique_digest']
  }
end
```

`puma.rb`:
```ruby

threads_count = ENV.fetch('RAILS_MAX_THREADS', 5)
threads threads_count, threads_count

port ENV.fetch('PORT', 3000)

environment ENV.fetch('RAILS_ENV', 'development')

workers ENV.fetch('WEB_CONCURRENCY', 2)

preload_app!

before_fork do
  puts 'Puma master process about to fork. Closing existing Active record connections.'
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.connection_pool.disconnect!

    ActiveRecord::Base.connection_pool.disable_query_cache! if Rails.env.development?
  end
end
```

`application_record.rb`:
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: {
    writing: :primary,
    reading: :primary_replica
  }
end
```

Is there a specific way we need to manage pool connections for a replica in Sidekiq?
